helm:
  parameters:
  - name: image.name
    value: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_registry
    forcestring: true
  - name: image.tag
    value: origin-main-49-bd6bedc
    forcestring: true
