replicaCount: 1
image:
  name: 911167924085.dkr.ecr.ap-northeast-2.amazonaws.com/forever_registry
  tag: latest
  pullPolicy: IfNotPresent

env:
  SPRING_DATASOURCE_URL: "jdbc:mysql://foreveryoung-us-aurora-db.global-gypwctyuwjqk.global.rds.amazonaws.com/forever_mysql_db"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_HIKARI_MAX_POOL_SIZE: "5"
  SPRING_HIKARI_MAX_IDLE: "2"

keda:
  enabled: true
  redis:
    address: redis://clustercfg.forever-event.td9wre.apn2.cache.amazonaws.com:6379
    listName: queue:outbox:point
    listLength: "10"

resources:
  requests:
    cpu: "1500m"     
    memory: "1024Mi" 
  limits:
    cpu: "2000m"     
    memory: "2048Mi" 

