apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-queue-scaler
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 50
  maxReplicaCount: 110
  triggers:
    - type: redis
      metadata:
        address: {{ .Values.keda.redis.address }}
        listName: {{ .Values.keda.redis.listName }}
        listLength: {{ .Values.keda.redis.listLength | quote }}
